services:
  # payload:
  #   image: node:20-alpine
  #   container_name: payload
  #   depends_on:
  #     - mongodb
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   labels:
  #     - 'traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000'
  #     - 'traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`${PROJECT_BASE_URL}`)'
  #   command: sh -c "corepack enable && corepack prepare pnpm@9.0.0 --activate && pnpm install && pnpm dev"

  mongodb:
    image: mongo:7
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo:/data/db
    logging:
      driver: none

volumes:
  mongo:
    name: mongo
